//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.Droid.ChatAppService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserServiceSoap", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class UserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UserService() {
            this.Url = "http://10.97.75.50/ChatAppWebInterface/UserService.asmx";
        }
        
        public UserService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetUsers", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUsers() {
            object[] results = this.Invoke("GetUsers", new object[0]);
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUsers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUsers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public User[] EndGetUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/CreateUser", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateUser(User item) {
            this.Invoke("CreateUser", new object[] {
                        item});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateUser(User item, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateUser", new object[] {
                        item}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateUser(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/EditUser", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditUser(User item) {
            this.Invoke("EditUser", new object[] {
                        item});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEditUser(User item, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EditUser", new object[] {
                        item}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndEditUser(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/DeleteUser", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUser(string id) {
            this.Invoke("DeleteUser", new object[] {
                        id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteUser(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteUser", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteUser(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/SendFriendRequest", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendFriendRequest(FriendRequest request) {
            this.Invoke("SendFriendRequest", new object[] {
                        request});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendFriendRequest(FriendRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendFriendRequest", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSendFriendRequest(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/ApproveFriendRequest", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveFriendRequest(FriendRequest request) {
            this.Invoke("ApproveFriendRequest", new object[] {
                        request});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginApproveFriendRequest(FriendRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ApproveFriendRequest", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndApproveFriendRequest(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetValidUser", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetValidUser(User user) {
            object[] results = this.Invoke("GetValidUser", new object[] {
                        user});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetValidUser(User user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetValidUser", new object[] {
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public User EndGetValidUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetMyRequests", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetMyRequests(string fromUserId) {
            object[] results = this.Invoke("GetMyRequests", new object[] {
                        fromUserId});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMyRequests(string fromUserId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMyRequests", new object[] {
                        fromUserId}, callback, asyncState);
        }
        
        /// <remarks/>
        public User[] EndGetMyRequests(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetMyFriends", RequestNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ResponseNamespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetMyFriends(string id) {
            object[] results = this.Invoke("GetMyFriends", new object[] {
                        id});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMyFriends(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMyFriends", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public User[] EndGetMyFriends(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class User {
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string EmailId;
        
        /// <remarks/>
        public string Password;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class FriendRequest {
        
        /// <remarks/>
        public string FromUserId;
        
        /// <remarks/>
        public string ToUserId;
        
        /// <remarks/>
        public FriendRequestStatus Status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public enum FriendRequestStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        PendingAction,
    }
}
