//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAppConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequest", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    [System.SerializableAttribute()]
    public partial class FriendRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToUserIdField;
        
        private ChatAppConsole.ServiceReference1.FriendRequestStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FromUserId {
            get {
                return this.FromUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FromUserIdField, value) != true)) {
                    this.FromUserIdField = value;
                    this.RaisePropertyChanged("FromUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ToUserId {
            get {
                return this.ToUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ToUserIdField, value) != true)) {
                    this.ToUserIdField = value;
                    this.RaisePropertyChanged("ToUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public ChatAppConsole.ServiceReference1.FriendRequestStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestStatus", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public enum FriendRequestStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingAction = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", ConfigurationName="ServiceReference1.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetUsers", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.GetUsersResponse GetUsers(ChatAppConsole.ServiceReference1.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetUsersResponse> GetUsersAsync(ChatAppConsole.ServiceReference1.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/CreateUser", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.CreateUserResponse CreateUser(ChatAppConsole.ServiceReference1.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.CreateUserResponse> CreateUserAsync(ChatAppConsole.ServiceReference1.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/EditUser", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.EditUserResponse EditUser(ChatAppConsole.ServiceReference1.EditUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/EditUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.EditUserResponse> EditUserAsync(ChatAppConsole.ServiceReference1.EditUserRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/DeleteUser", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.DeleteUserResponse DeleteUser(ChatAppConsole.ServiceReference1.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.DeleteUserResponse> DeleteUserAsync(ChatAppConsole.ServiceReference1.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/SendFriendRequest", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.SendFriendRequestResponse SendFriendRequest(ChatAppConsole.ServiceReference1.SendFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/SendFriendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.SendFriendRequestResponse> SendFriendRequestAsync(ChatAppConsole.ServiceReference1.SendFriendRequestRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/ApproveFriendRequest", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.ApproveFriendRequestResponse ApproveFriendRequest(ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/ApproveFriendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.ApproveFriendRequestResponse> ApproveFriendRequestAsync(ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetValidUser", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.GetValidUserResponse GetValidUser(ChatAppConsole.ServiceReference1.GetValidUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetValidUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetValidUserResponse> GetValidUserAsync(ChatAppConsole.ServiceReference1.GetValidUserRequest request);
        
        // CODEGEN: Generating message contract since element name fromUserId from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetMyRequests", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.GetMyRequestsResponse GetMyRequests(ChatAppConsole.ServiceReference1.GetMyRequestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetMyRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetMyRequestsResponse> GetMyRequestsAsync(ChatAppConsole.ServiceReference1.GetMyRequestsRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://10.97.75.50/ChatAppWebInterface/UserService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetMyFriends", ReplyAction="*")]
        ChatAppConsole.ServiceReference1.GetMyFriendsResponse GetMyFriends(ChatAppConsole.ServiceReference1.GetMyFriendsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.97.75.50/ChatAppWebInterface/UserService.asmx/GetMyFriends", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetMyFriendsResponse> GetMyFriendsAsync(ChatAppConsole.ServiceReference1.GetMyFriendsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(ChatAppConsole.ServiceReference1.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(ChatAppConsole.ServiceReference1.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(ChatAppConsole.ServiceReference1.User[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(ChatAppConsole.ServiceReference1.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User item;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(ChatAppConsole.ServiceReference1.User item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(ChatAppConsole.ServiceReference1.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateUserResponseBody {
        
        public CreateUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUser", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.EditUserRequestBody Body;
        
        public EditUserRequest() {
        }
        
        public EditUserRequest(ChatAppConsole.ServiceReference1.EditUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class EditUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User item;
        
        public EditUserRequestBody() {
        }
        
        public EditUserRequestBody(ChatAppConsole.ServiceReference1.User item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUserResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.EditUserResponseBody Body;
        
        public EditUserResponse() {
        }
        
        public EditUserResponse(ChatAppConsole.ServiceReference1.EditUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditUserResponseBody {
        
        public EditUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(ChatAppConsole.ServiceReference1.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(ChatAppConsole.ServiceReference1.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteUserResponseBody {
        
        public DeleteUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFriendRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFriendRequest", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.SendFriendRequestRequestBody Body;
        
        public SendFriendRequestRequest() {
        }
        
        public SendFriendRequestRequest(ChatAppConsole.ServiceReference1.SendFriendRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class SendFriendRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.FriendRequest request;
        
        public SendFriendRequestRequestBody() {
        }
        
        public SendFriendRequestRequestBody(ChatAppConsole.ServiceReference1.FriendRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFriendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFriendRequestResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.SendFriendRequestResponseBody Body;
        
        public SendFriendRequestResponse() {
        }
        
        public SendFriendRequestResponse(ChatAppConsole.ServiceReference1.SendFriendRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendFriendRequestResponseBody {
        
        public SendFriendRequestResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveFriendRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveFriendRequest", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.ApproveFriendRequestRequestBody Body;
        
        public ApproveFriendRequestRequest() {
        }
        
        public ApproveFriendRequestRequest(ChatAppConsole.ServiceReference1.ApproveFriendRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class ApproveFriendRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.FriendRequest request;
        
        public ApproveFriendRequestRequestBody() {
        }
        
        public ApproveFriendRequestRequestBody(ChatAppConsole.ServiceReference1.FriendRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveFriendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveFriendRequestResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.ApproveFriendRequestResponseBody Body;
        
        public ApproveFriendRequestResponse() {
        }
        
        public ApproveFriendRequestResponse(ChatAppConsole.ServiceReference1.ApproveFriendRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ApproveFriendRequestResponseBody {
        
        public ApproveFriendRequestResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidUser", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetValidUserRequestBody Body;
        
        public GetValidUserRequest() {
        }
        
        public GetValidUserRequest(ChatAppConsole.ServiceReference1.GetValidUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetValidUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User user;
        
        public GetValidUserRequestBody() {
        }
        
        public GetValidUserRequestBody(ChatAppConsole.ServiceReference1.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidUserResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetValidUserResponseBody Body;
        
        public GetValidUserResponse() {
        }
        
        public GetValidUserResponse(ChatAppConsole.ServiceReference1.GetValidUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetValidUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User GetValidUserResult;
        
        public GetValidUserResponseBody() {
        }
        
        public GetValidUserResponseBody(ChatAppConsole.ServiceReference1.User GetValidUserResult) {
            this.GetValidUserResult = GetValidUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyRequestsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyRequests", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetMyRequestsRequestBody Body;
        
        public GetMyRequestsRequest() {
        }
        
        public GetMyRequestsRequest(ChatAppConsole.ServiceReference1.GetMyRequestsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetMyRequestsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromUserId;
        
        public GetMyRequestsRequestBody() {
        }
        
        public GetMyRequestsRequestBody(string fromUserId) {
            this.fromUserId = fromUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyRequestsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyRequestsResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetMyRequestsResponseBody Body;
        
        public GetMyRequestsResponse() {
        }
        
        public GetMyRequestsResponse(ChatAppConsole.ServiceReference1.GetMyRequestsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetMyRequestsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User[] GetMyRequestsResult;
        
        public GetMyRequestsResponseBody() {
        }
        
        public GetMyRequestsResponseBody(ChatAppConsole.ServiceReference1.User[] GetMyRequestsResult) {
            this.GetMyRequestsResult = GetMyRequestsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyFriendsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyFriends", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetMyFriendsRequestBody Body;
        
        public GetMyFriendsRequest() {
        }
        
        public GetMyFriendsRequest(ChatAppConsole.ServiceReference1.GetMyFriendsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetMyFriendsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetMyFriendsRequestBody() {
        }
        
        public GetMyFriendsRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyFriendsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyFriendsResponse", Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx", Order=0)]
        public ChatAppConsole.ServiceReference1.GetMyFriendsResponseBody Body;
        
        public GetMyFriendsResponse() {
        }
        
        public GetMyFriendsResponse(ChatAppConsole.ServiceReference1.GetMyFriendsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.97.75.50/ChatAppWebInterface/UserService.asmx")]
    public partial class GetMyFriendsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatAppConsole.ServiceReference1.User[] GetMyFriendsResult;
        
        public GetMyFriendsResponseBody() {
        }
        
        public GetMyFriendsResponseBody(ChatAppConsole.ServiceReference1.User[] GetMyFriendsResult) {
            this.GetMyFriendsResult = GetMyFriendsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : ChatAppConsole.ServiceReference1.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<ChatAppConsole.ServiceReference1.UserServiceSoap>, ChatAppConsole.ServiceReference1.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.GetUsersResponse ChatAppConsole.ServiceReference1.UserServiceSoap.GetUsers(ChatAppConsole.ServiceReference1.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public ChatAppConsole.ServiceReference1.User[] GetUsers() {
            ChatAppConsole.ServiceReference1.GetUsersRequest inValue = new ChatAppConsole.ServiceReference1.GetUsersRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetUsersRequestBody();
            ChatAppConsole.ServiceReference1.GetUsersResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetUsersResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.GetUsersAsync(ChatAppConsole.ServiceReference1.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetUsersResponse> GetUsersAsync() {
            ChatAppConsole.ServiceReference1.GetUsersRequest inValue = new ChatAppConsole.ServiceReference1.GetUsersRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetUsersRequestBody();
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.CreateUserResponse ChatAppConsole.ServiceReference1.UserServiceSoap.CreateUser(ChatAppConsole.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public void CreateUser(ChatAppConsole.ServiceReference1.User item) {
            ChatAppConsole.ServiceReference1.CreateUserRequest inValue = new ChatAppConsole.ServiceReference1.CreateUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.CreateUserRequestBody();
            inValue.Body.item = item;
            ChatAppConsole.ServiceReference1.CreateUserResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).CreateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.CreateUserResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.CreateUserAsync(ChatAppConsole.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.CreateUserResponse> CreateUserAsync(ChatAppConsole.ServiceReference1.User item) {
            ChatAppConsole.ServiceReference1.CreateUserRequest inValue = new ChatAppConsole.ServiceReference1.CreateUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.CreateUserRequestBody();
            inValue.Body.item = item;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.EditUserResponse ChatAppConsole.ServiceReference1.UserServiceSoap.EditUser(ChatAppConsole.ServiceReference1.EditUserRequest request) {
            return base.Channel.EditUser(request);
        }
        
        public void EditUser(ChatAppConsole.ServiceReference1.User item) {
            ChatAppConsole.ServiceReference1.EditUserRequest inValue = new ChatAppConsole.ServiceReference1.EditUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.EditUserRequestBody();
            inValue.Body.item = item;
            ChatAppConsole.ServiceReference1.EditUserResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).EditUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.EditUserResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.EditUserAsync(ChatAppConsole.ServiceReference1.EditUserRequest request) {
            return base.Channel.EditUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.EditUserResponse> EditUserAsync(ChatAppConsole.ServiceReference1.User item) {
            ChatAppConsole.ServiceReference1.EditUserRequest inValue = new ChatAppConsole.ServiceReference1.EditUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.EditUserRequestBody();
            inValue.Body.item = item;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).EditUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.DeleteUserResponse ChatAppConsole.ServiceReference1.UserServiceSoap.DeleteUser(ChatAppConsole.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public void DeleteUser(string id) {
            ChatAppConsole.ServiceReference1.DeleteUserRequest inValue = new ChatAppConsole.ServiceReference1.DeleteUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.id = id;
            ChatAppConsole.ServiceReference1.DeleteUserResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).DeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.DeleteUserResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.DeleteUserAsync(ChatAppConsole.ServiceReference1.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.DeleteUserResponse> DeleteUserAsync(string id) {
            ChatAppConsole.ServiceReference1.DeleteUserRequest inValue = new ChatAppConsole.ServiceReference1.DeleteUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.DeleteUserRequestBody();
            inValue.Body.id = id;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.SendFriendRequestResponse ChatAppConsole.ServiceReference1.UserServiceSoap.SendFriendRequest(ChatAppConsole.ServiceReference1.SendFriendRequestRequest request) {
            return base.Channel.SendFriendRequest(request);
        }
        
        public void SendFriendRequest(ChatAppConsole.ServiceReference1.FriendRequest request) {
            ChatAppConsole.ServiceReference1.SendFriendRequestRequest inValue = new ChatAppConsole.ServiceReference1.SendFriendRequestRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.SendFriendRequestRequestBody();
            inValue.Body.request = request;
            ChatAppConsole.ServiceReference1.SendFriendRequestResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).SendFriendRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.SendFriendRequestResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.SendFriendRequestAsync(ChatAppConsole.ServiceReference1.SendFriendRequestRequest request) {
            return base.Channel.SendFriendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.SendFriendRequestResponse> SendFriendRequestAsync(ChatAppConsole.ServiceReference1.FriendRequest request) {
            ChatAppConsole.ServiceReference1.SendFriendRequestRequest inValue = new ChatAppConsole.ServiceReference1.SendFriendRequestRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.SendFriendRequestRequestBody();
            inValue.Body.request = request;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).SendFriendRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.ApproveFriendRequestResponse ChatAppConsole.ServiceReference1.UserServiceSoap.ApproveFriendRequest(ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest request) {
            return base.Channel.ApproveFriendRequest(request);
        }
        
        public void ApproveFriendRequest(ChatAppConsole.ServiceReference1.FriendRequest request) {
            ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest inValue = new ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.ApproveFriendRequestRequestBody();
            inValue.Body.request = request;
            ChatAppConsole.ServiceReference1.ApproveFriendRequestResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).ApproveFriendRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.ApproveFriendRequestResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.ApproveFriendRequestAsync(ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest request) {
            return base.Channel.ApproveFriendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.ApproveFriendRequestResponse> ApproveFriendRequestAsync(ChatAppConsole.ServiceReference1.FriendRequest request) {
            ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest inValue = new ChatAppConsole.ServiceReference1.ApproveFriendRequestRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.ApproveFriendRequestRequestBody();
            inValue.Body.request = request;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).ApproveFriendRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.GetValidUserResponse ChatAppConsole.ServiceReference1.UserServiceSoap.GetValidUser(ChatAppConsole.ServiceReference1.GetValidUserRequest request) {
            return base.Channel.GetValidUser(request);
        }
        
        public ChatAppConsole.ServiceReference1.User GetValidUser(ChatAppConsole.ServiceReference1.User user) {
            ChatAppConsole.ServiceReference1.GetValidUserRequest inValue = new ChatAppConsole.ServiceReference1.GetValidUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetValidUserRequestBody();
            inValue.Body.user = user;
            ChatAppConsole.ServiceReference1.GetValidUserResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetValidUser(inValue);
            return retVal.Body.GetValidUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetValidUserResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.GetValidUserAsync(ChatAppConsole.ServiceReference1.GetValidUserRequest request) {
            return base.Channel.GetValidUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetValidUserResponse> GetValidUserAsync(ChatAppConsole.ServiceReference1.User user) {
            ChatAppConsole.ServiceReference1.GetValidUserRequest inValue = new ChatAppConsole.ServiceReference1.GetValidUserRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetValidUserRequestBody();
            inValue.Body.user = user;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetValidUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.GetMyRequestsResponse ChatAppConsole.ServiceReference1.UserServiceSoap.GetMyRequests(ChatAppConsole.ServiceReference1.GetMyRequestsRequest request) {
            return base.Channel.GetMyRequests(request);
        }
        
        public ChatAppConsole.ServiceReference1.User[] GetMyRequests(string fromUserId) {
            ChatAppConsole.ServiceReference1.GetMyRequestsRequest inValue = new ChatAppConsole.ServiceReference1.GetMyRequestsRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetMyRequestsRequestBody();
            inValue.Body.fromUserId = fromUserId;
            ChatAppConsole.ServiceReference1.GetMyRequestsResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetMyRequests(inValue);
            return retVal.Body.GetMyRequestsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetMyRequestsResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.GetMyRequestsAsync(ChatAppConsole.ServiceReference1.GetMyRequestsRequest request) {
            return base.Channel.GetMyRequestsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetMyRequestsResponse> GetMyRequestsAsync(string fromUserId) {
            ChatAppConsole.ServiceReference1.GetMyRequestsRequest inValue = new ChatAppConsole.ServiceReference1.GetMyRequestsRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetMyRequestsRequestBody();
            inValue.Body.fromUserId = fromUserId;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetMyRequestsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatAppConsole.ServiceReference1.GetMyFriendsResponse ChatAppConsole.ServiceReference1.UserServiceSoap.GetMyFriends(ChatAppConsole.ServiceReference1.GetMyFriendsRequest request) {
            return base.Channel.GetMyFriends(request);
        }
        
        public ChatAppConsole.ServiceReference1.User[] GetMyFriends(string id) {
            ChatAppConsole.ServiceReference1.GetMyFriendsRequest inValue = new ChatAppConsole.ServiceReference1.GetMyFriendsRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetMyFriendsRequestBody();
            inValue.Body.id = id;
            ChatAppConsole.ServiceReference1.GetMyFriendsResponse retVal = ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetMyFriends(inValue);
            return retVal.Body.GetMyFriendsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetMyFriendsResponse> ChatAppConsole.ServiceReference1.UserServiceSoap.GetMyFriendsAsync(ChatAppConsole.ServiceReference1.GetMyFriendsRequest request) {
            return base.Channel.GetMyFriendsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatAppConsole.ServiceReference1.GetMyFriendsResponse> GetMyFriendsAsync(string id) {
            ChatAppConsole.ServiceReference1.GetMyFriendsRequest inValue = new ChatAppConsole.ServiceReference1.GetMyFriendsRequest();
            inValue.Body = new ChatAppConsole.ServiceReference1.GetMyFriendsRequestBody();
            inValue.Body.id = id;
            return ((ChatAppConsole.ServiceReference1.UserServiceSoap)(this)).GetMyFriendsAsync(inValue);
        }
    }
}
